### ISSUE TITLE
[php] variable via entrypoint/env

### ISSUE THREAD

**Issue by talset** [TimWolla/docker-adminer#49]
It would be nice to be able to change your default php setting (https://github.com/TimWolla/docker-adminer/blob/master/4/fastcgi/Dockerfile#L3-L7)

You should be able to handle them in the entrypoint by changing the `/usr/local/etc/php/conf.d/0-upload_large_dumps.ini` or put an example of how to to provide the param via the php cli `php "$@`

**Comment by TimWolla** [comment]
See https://github.com/TimWolla/docker-adminer/issues/36#issuecomment-415800670 and https://github.com/docker-library/php/issues/765#issuecomment-450697970

**Comment by talset** [comment]
> See [#36 (comment)](https://github.com/TimWolla/docker-adminer/issues/36#issuecomment-415800670) and [docker-library/php#765 (comment)](https://github.com/docker-library/php/issues/765#issuecomment-450697970)

I read the comments but I'm sorry it is still note "fixed". It would be nice to have a proper solution to set php limits via variables (not workaround). Or at least having something documented on github or hub.docker.

**Comment by TimWolla** [comment]
> It would be nice to have a proper solution to set php limits via variables (not workaround)

Using Docker's features to create your own image off an existing image is not a workaround. Using PHP's feature to read environment variables in php.ini is not a workaround either.
I'm not going to special case this image by adding support to override arbitrary configuration values and I'm not going to special case specific configuration values, because there will always be someone that _just_ needs to override _one_ more configuration value.
What I am going to (and what I did) is setting sane default values after previous user requests, because users successfully convinced me that e.g. the default `upload_max_filesize` of 2 MB is a bit low.

See also this (different) comment from #36 (especially the last paragraph): https://github.com/TimWolla/docker-adminer/issues/36#issuecomment-399584096

> Or at least having something documented on github or hub.docker.

Environments differ greatly. Some users are best suited by building their own image, some prefer to just bind-mount a single file into the container. When using the FastCGI version the web server (e.g. nginx) might need to be reconfigured as well.

There's enough documentation on how PHP works out in the Internet. Changing the configuration is even explained in the documentation for PHP's image on Docker Hub: https://hub.docker.com/_/php/#configuration. I made sure to prefix my configuration file with `0` to make sure it is being loaded first and easily overriden.
