### ISSUE TITLE
Boostrap bundled as a theme

### ISSUE THREAD

**Issue by dhsrocha** [TimWolla/docker-adminer#53]
Is there a possibility to add https://github.com/natanfelles/adminer-bootstrap-like not as an add-on but as a design option (or event as the default)?

**Comment by TimWolla** [comment]
This Docker image ships a stock adminer (with a few small modifications to make it more useful within Docker). I'm not going to add any third party add-ons, because I don't want to endorse any of them. 

Regarding that design specifically: It is no simple design (“just CSS”), but requires a dedicated plugin as well. On top of that it provides an index.php that not only enables the design, but rather a bunch of other plugins as well. It's more of an opinionated “Admin Suite” than a design.
