### ISSUE TITLE
Executable file not found

### ISSUE THREAD

**Issue by leopoldinelolcat** [TimWolla/docker-adminer#60]
Hi !
I got a problem with actual Dockerfile.
I got this error when I docker compose : 

> ERROR: for adminer  Cannot start service adminer: OCI runtime create failed: container_linux.go:345: starting container process caused "exec: \"entrypoint.sh\": executable file not found in $PATH": unknown

I have to fix the Dockerfile with this line : 
> RUN chmod +x /usr/local/bin/entrypoint.sh

Is this normal that actual Dockerfile doesn't set a chmod +x ?

**Comment by TimWolla** [comment]
Yes, this is intentional. The file has the executable bit within the git
repository and git is expected to chmod +x the file automatically when
cloning and checking out the repository. You might want to check why your
git does not do this.

If you run Windows this might be the cause, I believe Windows does not have
the concept of an executable bit. I can't confirm that, though.

leopoldine.lolcat <notifications@github.com> schrieb am Do., 19. Sep. 2019,
14:53:
