### ISSUE TITLE
Default language

### ISSUE THREAD

**Issue by svaldivia2** [TimWolla/docker-adminer#67]
There is a way to select a different default language than English?

I searched here:
https://www.adminer.org/plugins/

But didn't find one to do that... there is a plugin or some workaround?

Thanks in advance!

**Comment by TimWolla** [comment]
I believe Adminer selects the language based on the browser's language preferences. In any case this is not something I can help with in this repository. I don't develop Adminer, I just package it as a Docker Official Image. Thus I'm closing this issue, because it is not related to the Docker specific stuff.
